eliminate false positives for bug 1253482
The previous query resulted in a hit anytime keystone failed to start,
which could have any number of causes. The issue documented in bug
1253482 is specifically the result of keystone attempting to start on
port 35357, failing due to an "Address already in use" (35357 resides in
the linux ephemeral port range), and logging the fatal condition to
CRITICAL.

The previous query resulted in hits against failed attempts to start
keystone with underlying causes like this one:

+ exec /bin/bash -c 'cd /opt/stack/new/keystone &&
/opt/stack/new/keystone/bin/keystone-all --config-file
/etc/keystone/keystone.conf --debug'
Traceback (most recent call last):
  File "/opt/stack/new/keystone/bin/keystone-all", line 36, in <module>
      import pbr.version
      ImportError: No module named pbr.version

http://logs.openstack.org/36/63236/5/gate/gate-tempest-dsvm-postgres-full/b05afa7/logs/screen-key.txt.gz

Change-Id: I7351e4181ac3323be91a8224429d71cd52b221ae